site_name: AutoML mljar-supervised 

theme:
    name: material
    #custom_dir: overrides
    favicon: images/favicon.png
    icon:
        repo: fontawesome/brands/github-square
        logo: fontawesome/solid/book-open
    palette:
        primary: blue


repo_url: https://github.com/mljar/mljar-supervised
repo_name: mljar-supervised

markdown_extensions:
    - pymdownx.highlight:
        use_pygments: true
    - toc:
        permalink: true
    - codehilite
    - pymdownx.tabbed
    - pymdownx.superfences
    - admonition
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - mkdocstrings

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/mljar/mljar-supervised
        - icon: fontawesome/brands/slack
          link: https://mljar-supervised.slack.com/join/shared_invite/zt-gkhfsvhw-H6LMKxxV5adeTmn9V7nbZw#/
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/MLJARofficial
        - icon: fontawesome/regular/lightbulb
          link: https://mljar.com
    font:
        - text: 'Ubuntu'
        - code: 'Ubuntu Mono'

edit_uri: https://github.com/mljar/docs/edit/master/docs/

copyright: Copyright © MLJAR, Inc.

nav:
  - Get started: index.md
  - Features: features.md
  - How can you help?: help.md
  - AutoML API: api.md
  - Tutorials:
    - Classify Titanic passangers: tutorials/titanic.md